services:
  - type: web
    name: asaliswad-backend
    env: node
    region: singapore # Change region if needed
    buildCommand: npm install
    startCommand: npx tsx src/index.ts
    envVars:
      - key: NODE_VERSION
        value: 20.x
