-- Supabase Database Schema Setup Script for Asali Swad E-Commerce
-- Production-Ready Security Hardened Version (Backend-Removal Compliant)

-- 1. Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    mrp NUMERIC,
    description TEXT,
    image_url TEXT,
    images JSONB DEFAULT '[]'::jsonb,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    brand TEXT,
    stock INTEGER DEFAULT 0,
    sku TEXT,
    low_stock_limit INTEGER DEFAULT 5,
    is_active BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'AVAILABLE',
    offers JSONB DEFAULT '[]'::jsonb,
    specifications JSONB DEFAULT '{}'::jsonb,
    packages JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT NOT NULL,
    product_details JSONB,
    order_status TEXT DEFAULT 'PENDING',
    payment_status TEXT DEFAULT 'PENDING',
    payment_method TEXT DEFAULT 'COD',
    razorpay_order_id TEXT,
    razorpay_payment_id TEXT,
    shipment_id TEXT,
    shiprocket_order_id TEXT,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Card Applications Table
CREATE TABLE IF NOT EXISTS public.card_applications (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    user_email TEXT,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT NOT NULL,
    card_type TEXT DEFAULT 'Silver',
    status TEXT DEFAULT 'PENDING',
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    card_number TEXT,
    expires_at TEXT,
    coins INTEGER DEFAULT 0
);

-- 6. User Addresses Table
CREATE TABLE IF NOT EXISTS public.user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    user_email TEXT,
    name TEXT,
    phone TEXT,
    address_line TEXT,
    city TEXT,
    state TEXT,
    pincode TEXT,
    is_default BOOLEAN DEFAULT FALSE,
    saved_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Store Settings Table
CREATE TABLE IF NOT EXISTS public.store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Notify Requests Table
CREATE TABLE IF NOT EXISTS public.notify_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Stock History Table
CREATE TABLE IF NOT EXISTS public.stock_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    change_amount INTEGER NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notify_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_history ENABLE ROW LEVEL SECURITY;

-- Clean existing policies to avoid duplicates
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
    END LOOP;
END $$;

-- A. PUBLIC READ POLICIES (Storefront Browsing)
CREATE POLICY "Public Read Active Products" ON public.products 
    FOR SELECT USING (is_active = true);

CREATE POLICY "Public Read Categories" ON public.categories 
    FOR SELECT USING (true);

CREATE POLICY "Public Read Store Settings" ON public.store_settings 
    FOR SELECT USING (true);

-- B. CUSTOMER ORDER & CHECKOUT POLICIES
CREATE POLICY "Anyone Can Place Orders" ON public.orders 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Users Read Own Orders" ON public.orders 
    FOR SELECT USING (
        auth.uid() = user_id 
        OR auth.role() = 'service_role'
    );

-- C. USER ADDRESS POLICIES (Strict Ownership)
CREATE POLICY "Users Read Own Addresses" ON public.user_addresses 
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users Insert Own Addresses" ON public.user_addresses 
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users Update Own Addresses" ON public.user_addresses 
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users Delete Own Addresses" ON public.user_addresses 
    FOR DELETE USING (auth.uid() = user_id);

-- D. CARD APPLICATIONS & NOTIFICATIONS
CREATE POLICY "Public Submit Card Application" ON public.card_applications 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Users Read Own Card Applications" ON public.card_applications 
    FOR SELECT USING (auth.uid() = user_id OR auth.role() = 'service_role');

CREATE POLICY "Public Submit Notify Request" ON public.notify_requests 
    FOR INSERT WITH CHECK (true);

-- E. SERVICE ROLE / ADMIN FULL ACCESS (Bypasses RLS via Service Role Key)
CREATE POLICY "Service Role Full Access Products" ON public.products FOR ALL TO service_role USING (true);
CREATE POLICY "Service Role Full Access Categories" ON public.categories FOR ALL TO service_role USING (true);
CREATE POLICY "Service Role Full Access Orders" ON public.orders FOR ALL TO service_role USING (true);
CREATE POLICY "Service Role Full Access Settings" ON public.store_settings FOR ALL TO service_role USING (true);
CREATE POLICY "Service Role Full Access Addresses" ON public.user_addresses FOR ALL TO service_role USING (true);
CREATE POLICY "Service Role Full Access Cards" ON public.card_applications FOR ALL TO service_role USING (true);
CREATE POLICY "Service Role Full Access Notifications" ON public.notify_requests FOR ALL TO service_role USING (true);
CREATE POLICY "Service Role Full Access Stock History" ON public.stock_history FOR ALL TO service_role USING (true);

-- ====================================================================
-- INITIAL SEED DATA & STORAGE
-- ====================================================================
INSERT INTO public.store_settings (key, value)
VALUES 
  ('billing', '{"free_shipping_min_order": 499, "standard_shipping_fee": 49, "cod_extra_charge": 30, "gst_percentage": 5}'::jsonb),
  ('global_cart_offer', '{"enabled": true, "threshold": 499, "discount_percentage": 10, "message": "Get 10% OFF on orders above ₹499!"}'::jsonb)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.categories (name)
VALUES ('Whole Spices'), ('Powdered Spices'), ('Blended Spices')
ON CONFLICT DO NOTHING;

-- Storage Bucket Setup for Product Images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Storage Read" ON storage.objects FOR SELECT USING (bucket_id = 'product-images');
CREATE POLICY "Service Role Storage Write" ON storage.objects FOR INSERT TO service_role WITH CHECK (bucket_id = 'product-images');
