services:
  - type: web
    name: asaliswad-is-back
    env: node
    region: singapore # Change region if needed
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.x
